name = "YYZRegistry"
uuid = "d46f0dca-35e3-409e-aca3-9825b5ccd416"
repo = "https://github.com/yiyuezhuo/YYZRegistry.git"
description = "yiyuezhuo repo registry"

[packages]
54e4aa61-68be-4ac6-9fad-ed7868cad30c = { name = "YPPL_Parser", path = "YPPL_Parser"}
f7755522-bb72-47e4-a4f1-ac7cf6a9e10b = { name = "YPPL_Diagnosis", path = "YPPL_Diagnosis"}